# Pandas

- Proviene de **panel data**
- Vino a traves de una extension Numpy
- Dirve para el manejo y analisis de estructura de datos
- Podemos manipular tablas numericas y series temporales
- Sitio web https://pandas.pydata.org/docs/

In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

# Series

Es un array unidireccional (1-D) etiquetado, puede contener cualquier tipom de dato

- Etiqueta 1 | Dato 1
- Etiqueta 2 | Dato 2
- Etiqueta 3 | ...

A estas etiquetas le llamaremos "indices"

Para crear una serie:

~~~
serie = pd.Series(Datos, indes=None)
~~~

Una serie se puede crear a partir de ciertos datos:
- Array-like
- dict-like
- escalar

index: array-like

In [5]:
datos = ["Sevilla","Huelva","Málaga","Cádiz"]
ciudades = pd.Series(datos)
print(ciudades)

0    Sevilla
1     Huelva
2     Málaga
3      Cádiz
dtype: object

In [6]:
etiquetas = ["s","h","m","c"]
ciudades = pd.Series(datos, index = etiquetas, name="Ciudades andaluzas")
print(ciudades)

s    Sevilla
h     Huelva
m     Málaga
c      Cádiz
Name: Ciudades andaluzas, dtype: object

In [7]:
dic = {"pan": 1.2, "arroz": 2.3, "patatas": 3.2}
lista_compra = pd.Series(dic, index= ["pan", "arroz"])
print(lista_compra)

pan      1.2
arroz    2.3
dtype: float64

In [8]:
etiquetas = ["a","b","c","d"]
poblacion = pd.Series(23, index=etiquetas)
print(poblacion)

a    23
b    23
c    23
d    23
dtype: int64

In [9]:
print(ciudades["s"])

Sevilla

In [12]:
print (ciudades[0])

Sevilla

/tmp/ipython-input-2396636779.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print (ciudades[0])

In [13]:
print(ciudades.iloc[0])

Sevilla

In [15]:
print(ciudades[["h","c"]])

h    Huelva
c     Cádiz
Name: Ciudades andaluzas, dtype: object

In [16]:
print (ciudades[:-2])

s    Sevilla
h     Huelva
Name: Ciudades andaluzas, dtype: object

# Actualizar datos

In [17]:
#Agregar nuevo valor
ciudades["j"] = "Jaén"
print(ciudades)

s    Sevilla
h     Huelva
m     Málaga
c      Cádiz
j       Jaén
Name: Ciudades andaluzas, dtype: object

In [18]:
ciudades["c"] = "Córdoba"
print(ciudades)

s    Sevilla
h     Huelva
m     Málaga
c    Córdoba
j       Jaén
Name: Ciudades andaluzas, dtype: object

In [19]:
#Con valores de otras series
otras_ciudades = pd.Series(["Huesca","Madrid","Toledo"], index = ["h","m","t"], name= "Ciudades de España")
ciudades.update(otras_ciudades)
print(ciudades)

s    Sevilla
h     Huesca
m     Madrid
c    Córdoba
j       Jaén
Name: Ciudades andaluzas, dtype: object

In [20]:
# Reemplazar valores
ciudades = ciudades.replace(["Sevilla","Córdoba","Madrird"], ("sopa","coliflor","macarrones"))
print(ciudades)

s        sopa
h      Huesca
m      Madrid
c    coliflor
j        Jaén
Name: Ciudades andaluzas, dtype: object

In [21]:
del ciudades["c"]
print(ciudades)

s      sopa
h    Huesca
m    Madrid
j      Jaén
Name: Ciudades andaluzas, dtype: object

# Operaciones

In [22]:
# Aplicar una expresión (vectorización)
s = pd.Series([1.2, 2.3, 3.4, 4.5])
s = s**2 - 10
print(s)

0    -8.56
1    -4.71
2     1.56
3    10.25
dtype: float64

#Tipo

In [28]:
s.dtype

dtype('float64')

In [30]:
print(ciudades.dtype) # verificación de tipo de dato

object

#Pertenencia

In [26]:
"s" in ciudades

True

In [27]:
"f" in ciudades

False

In [34]:
print(ciudades["x"]) # Da fallo porque no existe

KeyError: 'x'

# Dataframes

Un data frame puede crearse a partir de:
- Un diccionario:
  - 1-D ndarray
  - Listas
  - diccionarios
  - series

- una lista de:
  - listas
  - series

- un ndarray 2-D:
- Otro Dataframe

In [64]:
# A partir de un diccionario de listas, sin idice:

pisos = {
    "m2":  [120, 85, 390],
    "precio": [185, 110, 450] # en miles de €
}

df_01 = pd.DataFrame(pisos)
print(df_01)

    m2  precio
0  120     185
1   85     110
2  390     450

In [65]:
# A partir de un diccionario de listas, con indices incluidos

pisos = {
    "m2":  [120, 85, 390],
    "precio": [185, 110, 450] # en miles de €
}

indices = ["piso1", "piso2", "piso3"]

df_02 = pd.DataFrame(pisos, index = indices)
print(df_02)

        m2  precio
piso1  120     185
piso2   85     110
piso3  390     450

In [76]:
# A partit de un ndarray 2-D

import numpy as np

datos = np.array([[1,2,3],[4,5,6]])

df_03 = pd.DataFrame(
    datos,
    columns = ["col1", "col2", "col3"],
    index = ["fil1", "fil2"]
    )

print(df_03)

      col1  col2  col3
fil1     1     2     3
fil2     4     5     6

# Escritura y lectura

Existen funciones para muchos formatos, por ejemplo:


~~~
dataframe = pd.read_json("fichero.json", sep=";") # Leer un fichero
dataframe.to_json ("fichero.json") # Guardamos el fichero
~~~

In [77]:
# Vamos a verlo en practica

df_03.to_csv("fichero_ejemplo.csv")

df_03_lectura = pd.read_csv("fichero_ejemplo.csv")
print(df_03_lectura)

  Unnamed: 0  col1  col2  col3
0       fil1     1     2     3
1       fil2     4     5     6

In [78]:
df_03.to_csv("fichero_ejemplo.csv")

df_03_lectura2 = pd.read_csv("fichero_ejemplo.csv", sep=",", index_col = 0)
display(df_03_lectura2)

      col1  col2  col3
fil1     1     2     3
fil2     4     5     6

In [82]:
df_03.to_csv("fichero_ejemplo.csv", index = False)

df_03_lectura3 = pd.read_csv("fichero_ejemplo.csv")
print(df_03_lectura3)

   col1  col2  col3
0     1     2     3
1     4     5     6

# Funciones de datos
1. df.head(): muestra las 5 primeras filas
2. df.head(n): muesta las primeras n filas
3. df.tail(): muestra las ultimas 5 filas
4. df.tail(n): muestra las ultimas n filas
5. df.info(): muestra un resumen con iformación general sobre el DataFrame. esto incluye:
    - Numero total de filas y columnas
    - nombre y tipo de cada columna
    - cantidad de valores nulos por columna
    - uso de memoria
6. df.describe(): muestra estadisticas descriptivas del DataFrame, incluyendo:
    - count (cantidad de valores nulos)
    - mean (media)
    - std (desviaciones estandar)
    - min (minimo)
    - 25% / 50% / 75% (percentiles)
7. df.dtypes: muestra los tipos de datos de cada columna
8. df.index: muestra etiquetas de los indices de los Data Frame
9. df.columns: muestra los nombres de las columnas de DataFrame

In [83]:
df_03_lectura2.describe()

          col1     col2     col3
count  2.00000  2.00000  2.00000
mean   2.50000  3.50000  4.50000
std    2.12132  2.12132  2.12132
min    1.00000  2.00000  3.00000
25%    1.75000  2.75000  3.75000
50%    2.50000  3.50000  4.50000
75%    3.25000  4.25000  5.25000
max    4.00000  5.00000  6.00000

# Seleccionar datos

Columna:
~~~
df("columna")
~~~

Crear una serie a partir de un DataFrame:
~~~
serie = df("columna")
~~~

Seleccionar varias columnas:
~~~
df[["col1", "col2", "col3"]]
~~~

Crear un DataFrame a partir de otro:
~~~
new_df = df[["col1", "col2", ...]]
~~~

Localizar filas por etiquetas:
~~~
df.loc["piso1"]
df.loc[["piso2", "piso4"]] # lista de etiquetas
df.loc["piso2": "piso7"] # rango de etiquetas
~~~

Localizar filas por posicion:
~~~
df.iloc[3] # localizar la fila por la posicion 3 (integer)
df.iloc[[2, 9]] # lista de posiciones
df.iloc[2:7] # rango de posiciones
~~~

# Actualizar informacion

Modificar un DataFrame con los valores de otro

In [85]:
df_04 = pd. DataFrame({"A": [1,2,3],
                       "B": [4,5,6]})
otro_df = pd.DataFrame({"B": [400,500,600],
                        "C": [7,8,9]})
display(df_04)
print("")

df_04.update(otro_df)
display(df_04)

   A  B
0  1  4
1  2  5
2  3  6

   A    B
0  1  400
1  2  500
2  3  600

In [90]:
pisos = {
    "m2":  [120, 85, 390],
    "precio": [185, 110, 450] # en miles de €
}

df_05 = pd.DataFrame(pisos)
display(df_05)
print("")
df_05 = df_05.replace([450], [999]) # reemplazara todos los 450 por 999
display(df_05)

    m2  precio
0  120     185
1   85     110
2  390     450

    m2  precio
0  120     185
1   85     110
2  390     999

# Crear columnas

Para crear columnas nuevas en un DataFrame ya existente:

In [91]:
data_base = {
    "calorias": [20,30,50,4],
    "pulso": [100,105,120,85]
}

df_06 = pd.DataFrame(data_base)

df_06["nueva_col"] = df_06["calorias"] * df_06["pulso"]
display(df_06)

   calorias  pulso  nueva_col
0        20    100       2000
1        30    105       3150
2        50    120       6000
3         4     85        340

In [95]:
data_base_02 = {
    "col1": [10,20,30],
    "col2": [40,50,60],
    "col3": [70,80,90]
}

df_07 = pd.DataFrame(data_base_02)
display(df_07)
print("")

df_07 = df_07.rename(
    columns = {
        "col1": "nuevo1",
        "col2": "nuevo2",
        "col3": "nuevo3"
        })

display(df_07)

   col1  col2  col3
0    10    40    70
1    20    50    80
2    30    60    90

   nuevo1  nuevo2  nuevo3
0      10      40      70
1      20      50      80
2      30      60      90

# Eliminar contenido del DataFrame

~~~
df.drop(label = None, axis = 0, inplace = False)
~~~

- labels: Lista de etiquetas o columnas
- axis:
    - 0 (eje X) -> etiqueta/indices
    - 1 (eje Y) -> columnas

In [97]:
# Eliminar columnas concretas
del df_06["pulso"]
display(df_06)

   calorias  nueva_col
0        20       2000
1        30       3150
2        50       6000
3         4        340

In [99]:
serie = df_06.pop("nueva_col")
display(serie)

0    2000
1    3150
2    6000
3     340
Name: nueva_col, dtype: int64

In [100]:
datos = {
    "codigo": ["AP", "BL", "CG"],
    "alumno": ["Antonio Pérez", "Bea López", "Cristina Garcia"],
    "nota": [8,7,9]
}

df_08 = pd.DataFrame(datos)
display(df_08)

# Establezcamos la acolumna codigo como indice
df_08_nuevo = df_08.set_index("codigo", drop = True, inplace = False)
display(df_08_nuevo)
# drop = True va a eliminar la columna "codigo" despues de establecer como indice (si fuera False, la mantendria)
# inplace = False crea una nueva copia del DataFrame sin modificar el original (si fuese True, el DataFrame original se modificaria)

print("\n DataFrame con 'codigo' como indice:")
display(df_08)

  codigo           alumno  nota
0     AP    Antonio Pérez     8
1     BL        Bea López     7
2     CG  Cristina Garcia     9

                 alumno  nota
codigo
AP        Antonio Pérez     8
BL            Bea López     7
CG      Cristina Garcia     9

 DataFrame con 'codigo' como indice:

  codigo           alumno  nota
0     AP    Antonio Pérez     8
1     BL        Bea López     7
2     CG  Cristina Garcia     9

# Otro ejemplo

In [101]:
indice = ["alum1", "alum2", "alum3"]

df_08_nuevo = df_08.set_index(pd.Index(indice), inplace = False)
print("\n DataFrame con indice personalizado:")
display(df_08_nuevo)

 DataFrame con indice personalizado:

      codigo           alumno  nota
alum1     AP    Antonio Pérez     8
alum2     BL        Bea López     7
alum3     CG  Cristina Garcia     9

# Filtros

In [104]:
datos_ejemplo = {
    "nombre": ["Adrian Pavón", "Pablo González", "Alberto Cárdeno"],
    "edad": [21,19,22],
    "ciudad": ["El Garrobo", "Tocina y los Rosales", "Cumbres Mayores"]
}

df_09 =pd.DataFrame(datos_ejemplo)

filtro = df_09["edad"] < 20 # duevuelve una serie booleana
df_filtrado = df_09[filtro] # aplica el filtro del DataFrame

display(df_filtrado)

           nombre  edad                ciudad
1  Pablo González    19  Tocina y los Rosales

In [108]:
# Filtrado de varias columnas

filtro1 = df_09["edad"] > 20
filtro2 = df_09["ciudad"] == "El Garrobo"

df_filtrado = df_09[filtro1 & filtro2]

display(df_filtrado)

         nombre  edad      ciudad
0  Adrian Pavón    21  El Garrobo

In [109]:
df_filtrado = df_09[filtro1 | filtro2]
display(df_filtrado)

            nombre  edad           ciudad
0     Adrian Pavón    21       El Garrobo
2  Alberto Cárdeno    22  Cumbres Mayores

In [110]:
# Veamos como aplicar filtros en ua lista:

valores = ["El Garrobo", "Cádiz"]
filtro = df_09["ciudad"].isin(valores)

df_filtrado = df_09[filtro]

display(df_filtrado)

         nombre  edad      ciudad
0  Adrian Pavón    21  El Garrobo

In [113]:
# Como filtrar valores conocidos (no nulos) o nulos:

# Crear un DataFrame con valores nulos:
datos_ejemplo = {
    "nombre": ["Antonio", "Alberto", None, "Lucas"],
    "edad": [21, 22, 22, None]
}

df_10 = pd.DataFrame(datos_ejemplo)


# Filtro donde nombre no sea nulo
df_no_nulo = df_10[df_10["nombre"].notna()]

# Filtro donde filas "edad" sea nulo
df_nulo = df_10[df_10["edad"].isna()]

print("\n DataFrame con nombres no nulos:")
display(df_no_nulo)

print("\n DataFrame con edades nulas:")
display(df_nulo)

 DataFrame con nombres no nulos:

    nombre  edad
0  Antonio  21.0
1  Alberto  22.0
3    Lucas   NaN

 DataFrame con edades nulas:

  nombre  edad
3  Lucas   NaN

RECUERDA: Para filtrar con valores exactos usariamos:

~~~
df[df["columna"] == valor]
~~~

In [116]:
if (df_10["edad"] == 21).any(): # verificara si hay al menos un True
    print("Hay personas de 21 años")

Hay personas de 21 años

In [117]:
# Podriamos usar un .all() para verificar si todas las filas cumplen una condicion
if (df_10["edad"] > 21).all():
  print("Todos son mayores de edad y tienen mas de 21 años")
else:
  print("No todos son mayores de 21")

No todos son mayores de 21